[package]
name = "conway"
version = "0.1.0"
authors = ["nebelgrau"]
edition = "2018"

[dependencies]

cortex-m = "0.6.1"
cortex-m-rt = "0.6.10"

stm32f4xx-hal = {version = "0.7.0", features = ["stm32f407", "rt"]}
stm32f4 = "0.9.0"

nb = "0.1.2"
bare-metal = {version = "0.2.5", features = ["const-fn"]}
embedded-hal = {version = "0.2.3", features = ["unproven"]}

panic-halt = "0.2.0"

ssd1306 = {version ="0.3.0", features=["graphics"]}
embedded-graphics = "0.6.0-alpha.3"

rand_core = "0.5.1"

arrayvec = {version = "0.5.1", default-features = false}



[profile.release]
debug = true
lto = true
opt-level = "z"